HOTT-3381-3384: Load exchange rates data
trade-tariff/trade-tariff-backend pull request #1342
Opened 2023-06-22 16:03 UTC by maverickvi

### Jira link

https://transformuk.atlassian.net/browse/HOTT-3381
https://transformuk.atlassian.net/browse/HOTT-3382
https://transformuk.atlassian.net/browse/HOTT-3383
https://transformuk.atlassian.net/browse/HOTT-3384
https://transformuk.atlassian.net/browse/HOTT-3483
https://transformuk.atlassian.net/browse/HOTT-3482

### What?

I have added/removed/altered:

- [ ] Added exchange rates data loaders

### Why?

I am doing this because:

- we need to display this data on the exchange rates frontend

### Deployment risks (optional)

- Includes destructive/migratory actions which may effect critical data

2023-06-23 09:08 UTC, jebw requested changes
Looks really good - nice a clean

One change I would suggest is changing the `.populate` methord to take the csv file as a parameter. It can still default to the one in the constant but that will avoid the need to `stub_const` in the specs which is poking into the class internals and isn't really needed in this case

A second observation is generally I try to group the migrations into one larger one - the rationale being that I want it to succeed or fail as a single unit and each migration runs in its own transaction. That isn't enough of a concern to be worth changing this though and its table additions if its half complete then we end up with orphan tables but that wont impact running code.

2023-06-23 09:08 UTC, jebw commented on app/models/exchange_rate_currency.rb
> +    def populate
`def populate(src = CURRENCY_FILE)`

2023-06-23 09:08 UTC, jebw commented on app/models/exchange_rate_currency.rb
> +      CSV.foreach(CURRENCY_FILE, headers: true) do |row|
`CSV.foreach(src, headers: true) do |row|`

2023-06-23 09:08 UTC, jebw commented on spec/models/exchange_rate_country_spec.rb
> +    described_class.populate
```ruby
described_class.populate Rails.root.join(csv_file)
```

2023-06-28 09:51 UTC, jebw submitted a review, later dismissed
LGTM

2023-06-28 10:17 UTC, willfish approved these changes

2023-06-28 13:13 UTC, merged