HOTT-4561: Categorisation API
trade-tariff/trade-tariff-backend pull request #1633
Opened 2023-12-14 11:30 UTC by rasikasri

### Jira link

[HOTT-4561]<https://transformuk.atlassian.net/browse/HOTT-4561>

### What?

I have added/removed/altered:

- [ ] Added a simple API to serialize all of the categorisation records

### Why?

I am doing this because:

- This will facilitate service like TSS to implement green lanes if they plan to fully recalculate the logic and use over night scrapes
-
-

### Have you? (optional)

- [ ] Added documentation for new apis
- [ ] Added new environment variables with correct values to all apps in all spaces

### Deployment risks (optional)

- Includes destructive/migratory actions which may effect critical data
- Changes an api that is used in production

2023-12-14 15:41 UTC, alexdesi commented on spec/serializers/api/v2/green_lanes/categorisation_serializer_spec.rb
> +        }]'
the indentation looks strange here

2023-12-14 15:57 UTC, alexdesi submitted a review, later dismissed
It looks good to me—just a minor comment.

2024-01-02 11:08 UTC, alexdesi commented on spec/serializers/api/v2/green_lanes/categorisation_serializer_spec.rb
> +        }]'
I safer approach is to use Ruby structure and convert it `to_json` :
```
[{
  "category"=>"1", 
  "regulation_id"=>"D0000001", 
  "measure_type_id"=>"400", 
  "geographical_area"=>"1000", 
  "document_codes"=>[], 
  "additional_codes"=>[]
}].to_json
```
This way the object is parsed and the json format is correct.

2024-01-02 14:28 UTC, jebw requested changes
LGTM - can you tweak the source JSON data in the spec - either amend the indendation or use a ruby hash with `.to_json` as @alexdesi suggested

If you're wanting to use a string, you can generate multiline strings with heredoc (but `.to_json` is a better approach), eg

```ruby
class SomeClass
  def some_method
    <<~ EOS
      {
        "key" => "value"
      }
    EOS
  end
end
```
```

2024-01-02 16:43 UTC, jebw approved these changes
LGTM :raised_hands:

2024-01-03 09:37 UTC, merged