Refactor measure presenter
trade-tariff/trade-tariff-backend pull request #278
Opened 2021-10-28 16:28 UTC by willfish

### Jira link

HOTT-<TODO>

### What?

I have added/removed/altered:

- [x] Refactor measure presenter

2021-11-01 14:56 UTC, jebw requested changes
Is it worth using `alias_method` for this - would shorten the delegation methods?

More signficantly it looks like there's a recursive call in the change so the specs are failing?

2021-11-02 14:21 UTC, willfish commented
Fixed the overflow

2021-11-02 14:22 UTC, willfish commented
Seems like alias_method works against self rather than __getobj__ or whatever the underlying method is so it KOs when you try

2021-11-04 17:05 UTC, jebw approved these changes

2021-11-04 17:05 UTC, merged