HOTT-1337: Obfuscate errors to clients of the backend apis
trade-tariff/trade-tariff-backend pull request #441
Opened 2022-02-28 15:30 UTC by willfish

### Jira link

https://transformuk.atlassian.net/browse/HOTT-1337

### What?

I have added/removed/altered:

- [x] Added specs of current error propagation behaviour
- [x] Altered the internal server error behaviour to not include the exception body

### Why?

I am doing this because:

- We were missing coverage of this
- We need to make sure that internal details of the service do not leak to clients

2022-02-28 15:54 UTC, jebw requested changes
Looks great but dropping the `consider_all_requests_local` will confuse things for other developers

2022-02-28 15:54 UTC, jebw commented on app/controllers/application_controller.rb
> -  unless Rails.application.config.consider_all_requests_local
I think this will confuse matters in development mode and prevent us from seeing the normal rails error message

2022-02-28 15:54 UTC, jebw commented on app/controllers/application_controller.rb
> +  rescue_from Exception,                          with: :render_internal_server_error
TBH the general rescue is wrong but thats doesn't really impact the scope of this PR

2022-02-28 17:17 UTC, jebw commented on app/controllers/application_controller.rb
> -  unless Rails.application.config.consider_all_requests_local
Isn't this `unless` to make sure these exceptions are not rescued in dev mode, so falling through to the default rails exception handler app

Without it, the dev mode will operate the same as prod mode without the red exceptions screens?

2022-02-28 17:27 UTC, willfish commented
That's what I understood, yeah. It clumsily applies to test, though, and I
wanted to make sure we had coverage of this behaviour. Possibly we could
control this more explicitly via an env var which defaults to having these
enabled for test and prod but disables for dev
(RESCUE_CONTROLLER_EXCEPTIONS or equivalent).

On Mon, 28 Feb 2022, 17:17 Jeb Wilkins, ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In app/controllers/application_controller.rb
> <https://github.com/trade-tariff/trade-tariff-backend/pull/441#discussion_r816092879>
> :
>
> > @@ -6,13 +6,11 @@ class ApplicationController < ActionController::Base
>    before_action :clear_association_queries
>    around_action :configure_time_machine
>
> -  unless Rails.application.config.consider_all_requests_local
>
> Isn't this unless to make sure these exceptions are not rescued in dev
> mode, so falling through to the default rails exception handler app
>
> Without it, the dev mode will operate the same as prod mode without the
> red exceptions screens?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/trade-tariff/trade-tariff-backend/pull/441#discussion_r816092879>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB6HNVHGAYCVIAI3CO5J4SLU5OU2TANCNFSM5PRNB73A>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-03-01 14:27 UTC, jebw approved these changes
LGTM :raised_hands:

2022-03-01 14:27 UTC, merged