HOTT-2048: Exposed API endpoints needed for measure_type page
trade-tariff/trade-tariff-backend pull request #825
Opened 2022-10-18 13:58 UTC by maverickvi

### Jira link

[HOTT-<2048>](https://transformuk.atlassian.net/browse/HOTT-2048)

### What?

I have added/removed/altered:

- [ ] Exposed API endpoints needed for measure_type page

### Why?

I am doing this because:

- We need access to measure_type and preference_code on the frontend

### Have you? (optional)

- [ ] Added documentation for new apis

### Deployment risks (optional)

- Changes an api that is used in production

<img width="1283" alt="Screenshot 2022-10-18 at 14 57 16" src="https://user-images.githubusercontent.com/12201130/196450575-3db63a61-f1cb-4d03-bae2-ed879cf6ef1e.png">

2022-10-18 14:11 UTC, jebw requested changes
Code looks good but could do with some extra checks in the specs

Also its crashing on boot so that will need resolving :+1:

2022-10-18 14:11 UTC, jebw commented on spec/requests/api/v2/preference_codes_controller_spec.rb
> +  describe 'GET #show' do
This could do with a spec for the failure case as well - checking it 404s

2022-10-18 14:11 UTC, jebw commented on spec/controllers/api/v2/measure_types_controller_spec.rb
> +      it { expect(do_request.body).to match_json_expression pattern }
This should check the status code is 404 as well

2022-10-18 14:11 UTC, jebw commented on spec/controllers/api/v2/measure_types_controller_spec.rb
> +      it { expect(do_request.body).to match_json_expression pattern }
This should check the endpoint returns a 200

2022-10-18 14:11 UTC, jebw commented on spec/controllers/api/v2/measure_types_controller_spec.rb
> +      it { expect(do_request.body).to match_json_expression pattern }
eg just a oneliner `it { is_expected.to have_http_status :success }`

2022-10-18 16:41 UTC, jebw approved these changes
LGTM

2022-10-19 09:00 UTC, willfish approved these changes

2022-10-20 12:21 UTC, merged